#!/bin/bash

echo "Setting /etc/hostname to $BUTTERKNIFE_HOSTNAME"
echo $BUTTERKNIFE_HOSTNAME > /etc/hostname

echo "Substituting /etc/hosts"
if [ -z "$BUTTERKNIFE_DOMAIN" ]; then
    sed -i -e "s/127\.0\.1\.1.*$/127.0.1.1 $BUTTERKNIFE_HOSTNAME/g" /etc/hosts
else
    sed -i -e "s/127\.0\.1\.1.*$/127.0.1.1 $BUTTERKNIFE_HOSTNAME.$BUTTERKNIFE_DOMAIN $BUTTERKNIFE_HOSTNAME/g" /etc/hosts
fi
