#!/bin/bash

SUBVOLUME="@persistent"
MOUNTPOINT=/var/persistent

if [ ! -d "$BUTTERKNIFE_POOL_MOUNTPOINT/$SUBVOLUME" ]; then
    echo "Creating subvolume $SUBVOLUME on $BUTTERKNIFE_POOL_MOUNTPOINT"
    btrfs subvolume create "$BUTTERKNIFE_POOL_MOUNTPOINT/$SUBVOLUME"
fi

echo "Mounting /var/persistent"
echo "UUID=$BUTTERKNIFE_POOL_UUID /var/persistent btrfs defaults,subvol=$SUBVOLUME 0 9" >> /etc/fstab
mkdir -p $MOUNTPOINT
mount $MOUNTPOINT
