#!/bin/bash

if [ ! -x /usr/bin/puppet ]; then
    echo "Puppet not installed, skipping Puppet agent state persistence"
    exit 0
fi

mkdir -p /var/lib/persistent/puppet/ssl/certs/

if [ -e /var/lib/puppet/ssl/certs/ca.pem ]; then
    echo "Copying Puppet CA certificate ..."
    cp /var/lib/puppet/ssl/certs/ca.pem /var/lib/persistent/puppet/ssl/certs/ca.pem
fi

chown puppet:puppet /var/lib/persistent/pupppet
chmod 750 /var/lib/persistent/puppet

# Substitute /var/lib/puppet with symlink to /var/lib/persistent/puppet
rm -Rf /var/lib/puppet
ln -s /var/lib/persistent/puppet /var/lib/puppet

puppet agent --enable

