#!/bin/bash

if [ -z "$BUTTERKNIFE_DOMAIN" ]; then
    echo "No BUTTERKNIFE_DOMAIN specified, skipping domain join"
    exit 255;
fi

BUTTERKNIFE_REALM=$(echo $BUTTERKNIFE_DOMAIN | tr '[:lower:]' '[:upper:]')

echo "Setting Kerberos5 realm to $BUTTERKNIFE_REALM"
sed -i -e "s/default_realm.*/default_realm = $BUTTERKNIFE_REALM/g" /etc/krb5.conf

echo "Substituting SSSD configuration"
rm -fv /etc/sssd/sssd.conf
ln -s /etc/sssd/conf.d/$BUTTERKNIFE_DOMAIN /etc/sssd/sssd.conf

if [ -f /etc/sudoers-available.d/$BUTTERKNIFE_DOMAIN ]; then
    echo "Symlinking /etc/sudoers-available.d/$BUTTERKNIFE to /etc/sudoers.d/domain-admins"
    ln -s /etc/sudoers-available.d/$BUTTERKNIFE_DOMAIN /etc/sudoers.d/domain-admins
    echo "Consider using sudo_provider=... in sssd.conf!"
fi
