#!/bin/bash

set -x
set -e

while :
do

    dialog --menu "Snapshot deployment finished, what would you like to do next?" 0 0 0 \
        reboot "Reboot machine" \
        join "Join domain" \
        user "Create local user" \
        passwd "Set root user password" \
        shell "Drop to shell" \
        2>/tmp/finish
            
    case $(cat /tmp/finish) in
        reboot)
            exit 0
        ;;
        join)
            winbind-join-domain
        ;;
        user)
            dialog --inputbox "Enter first name" 0 0 2>/tmp/given_name
            dialog --inputbox "Enter last name" 0 0 2>/tmp/surname
            dialog --inputbox "Enter username" 0 0 "$(cat /tmp/given_name | tr '[:upper:]' '[:lower:]')" 2>/tmp/username
            # Assume tmpfs is mounted at /tmp !!!
            USERNAME="$(cat /tmp/username)"
            adduser --disabled-password --gecos "$(cat /tmp/given_name) $(cat /tmp/surname),,," $USERNAME
            
            while :
            do
                dialog --insecure --passwordbox "Enter password for $USERNAME" 0 0 2>/tmp/passwd
                echo -en "\n$(cat /tmp/passwd)\n$(cat /tmp/passwd)\n" | passwd $USERNAME
                if [ "$?" == "0" ]; then
                    break
                fi
            done
        ;;
        passwd)
            passwd root
        ;;
        shell)
            bash
        ;;
    esac
done
